# Generated by Django 5.2.17 on 2026-08-13 04:00

import apps.projects.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_number', models.CharField(default=apps.projects.models.generate_project_number, editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('WAITING_CLIENT', 'Waiting for client'), ('IN_PROGRESS', 'In progress'), ('REVIEW', 'Review'), ('REVISION', 'Revision'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On hold'), ('CANCELLED', 'Cancelled')], default='PLANNING', max_length=24)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='crm.contact')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.organization')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='sales.quote')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.store')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes requested'), ('REJECTED', 'Rejected')], default='PENDING', max_length=24)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_note', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_project_approvals', to=settings.AUTH_USER_MODEL)),
                ('requested_from_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_approvals', to='crm.contact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='projects.project')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.projects.models.project_file_upload_to)),
                ('name', models.CharField(max_length=220)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Internal'), ('CUSTOMER', 'Customer')], default='INTERNAL', max_length=16)),
                ('category', models.CharField(choices=[('REQUIREMENT', 'Requirement'), ('DESIGN', 'Design'), ('DELIVERABLE', 'Deliverable'), ('CONTRACT', 'Contract'), ('REFERENCE', 'Reference'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('INTERNAL', 'Internal'), ('CUSTOMER', 'Customer')], default='INTERNAL', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_updates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='projects.projectstage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['contact', 'status', '-updated_at'], name='projects_pr_contact_b52368_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['manager', 'status', '-updated_at'], name='projects_pr_manager_bc6b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['store', 'status'], name='projects_pr_store_i_388a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['target_completion_date', 'status'], name='projects_pr_target__e617c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percentage__gte', 0), ('progress_percentage__lte', 100)), name='projects_progress_between_0_100'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['project', 'status', '-requested_at'], name='projects_ap_project_57f102_idx'),
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['requested_from_contact', 'status', '-requested_at'], name='projects_ap_request_83669c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['project', 'visibility', 'category', '-created_at'], name='projects_pr_project_547eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstage',
            index=models.Index(fields=['project', 'status', 'sort_order'], name='projects_pr_project_87602e_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectstage',
            constraint=models.UniqueConstraint(fields=('project', 'sort_order'), name='projects_unique_stage_order'),
        ),
        migrations.AddIndex(
            model_name='projectupdate',
            index=models.Index(fields=['project', 'visibility', '-created_at'], name='projects_pr_project_8de4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='projectupdate',
            index=models.Index(fields=['stage', '-created_at'], name='projects_pr_stage_i_ed045c_idx'),
        ),
    ]
