# Generated by Django 5.2.17 on 2026-08-13 04:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=320)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='services/categories/')),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='services_se_is_acti_fd8993_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(max_length=360)),
                ('description', models.TextField()),
                ('price_type', models.CharField(choices=[('FIXED', 'Fixed'), ('STARTING_FROM', 'Starting from'), ('QUOTE', 'Request quote'), ('FREE', 'Free')], max_length=32)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('delivery_time', models.CharField(blank=True, max_length=120)),
                ('scope', models.TextField(blank=True)),
                ('exclusions', models.TextField(blank=True)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('process', models.JSONField(blank=True, default=list)),
                ('revision_policy', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='services/featured/')),
                ('gallery_data', models.JSONField(blank=True, default=list)),
                ('action_type', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('REQUEST_QUOTE', 'Request quote'), ('INTERNAL_CHECKOUT', 'Internal checkout'), ('EXTERNAL_CHECKOUT', 'External checkout'), ('DISABLED', 'Disabled')], default='WHATSAPP', max_length=32)),
                ('action_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['category__sort_order', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active', 'sort_order'], name='services_se_categor_1b8fc9_idx'), models.Index(fields=['is_featured', 'is_active'], name='services_se_is_feat_fb2165_idx'), models.Index(fields=['price_type'], name='services_se_price_t_caa3ad_idx')],
            },
        ),
    ]
