REQUIRED_PAGES = (
    "index.html",
    "services.html",
    "ecommerce.html",
    "websites.html",
    "brand-content.html",
    "growth.html",
    "custom-systems.html",
    "tharaa.html",
    "portfolio.html",
    "knowledge.html",
    "about.html",
    "contact.html",
    "store-launch.html",
    "storefront-customization.html",
    "store-redesign.html",
    "product-page-optimization.html",
    "ecommerce-growth.html",
    "ecommerce-support.html",
    "404.html",
)

RETIRED_PLATFORM_PAGES = (
    "salla.html",
    "zid.html",
    "shopify.html",
    "woocommerce.html",
    "wordpress.html",
)

CLEAN_ALIASES = {
    "": "index.html",
    "services/": "services.html",
    "ecommerce/": "ecommerce.html",
    "websites/": "websites.html",
    "brand-content/": "brand-content.html",
    "growth/": "growth.html",
    "custom-systems/": "custom-systems.html",
    "tharaa/": "tharaa.html",
    "portfolio/": "portfolio.html",
    "knowledge/": "knowledge.html",
    "about/": "about.html",
    "contact/": "contact.html",
    "store-launch/": "store-launch.html",
    "storefront-customization/": "storefront-customization.html",
    "store-redesign/": "store-redesign.html",
    "product-page-optimization/": "product-page-optimization.html",
    "ecommerce-growth/": "ecommerce-growth.html",
    "ecommerce-support/": "ecommerce-support.html",
}
