# Generated by Django 5.2.17 on 2026-08-13 04:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PAID_SOCIAL', 'Paid social'), ('SEARCH', 'Search'), ('SEO', 'SEO'), ('PARTNERSHIP', 'Partnership'), ('REFERRAL', 'Referral'), ('OTHER', 'Other')], max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'channel', '-created_at'], name='marketing_c_status_c80e82_idx'), models.Index(fields=['utm_campaign'], name='marketing_c_utm_cam_5e8506_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttributionTouch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_session_id', models.CharField(blank=True, max_length=64)),
                ('touch_type', models.CharField(choices=[('FIRST_TOUCH', 'First touch'), ('TOUCH', 'Touch'), ('CONVERSION_TOUCH', 'Conversion touch')], default='TOUCH', max_length=24)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('medium', models.CharField(blank=True, max_length=120)),
                ('campaign_name', models.CharField(blank=True, max_length=160)),
                ('landing_page', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_touches', to='crm.contact')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touches', to='marketing.campaign')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['contact', '-occurred_at'], name='marketing_a_contact_711020_idx'), models.Index(fields=['campaign', 'touch_type', '-occurred_at'], name='marketing_a_campaig_62d03a_idx'), models.Index(fields=['anonymous_session_id', '-occurred_at'], name='marketing_a_anonymo_3f2a0e_idx')],
            },
        ),
    ]
