# Generated by Django 5.2.17 on 2026-08-13 04:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('lifecycle_stage', models.CharField(choices=[('LEAD', 'Lead'), ('QUALIFIED', 'Qualified'), ('CUSTOMER', 'Customer'), ('REPEAT_CUSTOMER', 'Repeat customer'), ('INACTIVE', 'Inactive')], default='LEAD', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('preferred_language', models.CharField(default='ar', max_length=8)),
                ('first_source', models.CharField(blank=True, max_length=120)),
                ('first_contact_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=16)),
                ('purpose', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('GRANTED', 'Granted'), ('WITHDRAWN', 'Withdrawn')], max_length=16)),
                ('source', models.CharField(max_length=120)),
                ('policy_version', models.CharField(max_length=40)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='crm.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('reference_type', models.CharField(blank=True, max_length=120)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activity_events', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='crm.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('legal_name', models.CharField(blank=True, max_length=220)),
                ('website', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'status'], name='crm_organiz_name_73fb57_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='crm.contact')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_links', to='crm.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('url', models.URLField(blank=True)),
                ('platform', models.CharField(choices=[('SALLA', 'Salla'), ('ZID', 'Zid'), ('SHOPIFY', 'Shopify'), ('WOOCOMMERCE', 'WooCommerce'), ('WORDPRESS', 'WordPress'), ('CUSTOM', 'Custom'), ('OTHER', 'Other')], max_length=32)),
                ('external_store_id', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='crm.organization')),
                ('primary_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='crm.contact')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='crm_contact_email_240305_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='crm_contact_phone_189db8_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['lifecycle_stage', 'status'], name='crm_contact_lifecyc_781274_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner', 'status'], name='crm_contact_owner_i_6db9c8_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-last_activity_at'], name='crm_contact_last_ac_4d6b93_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['contact', 'channel', 'purpose', '-created_at'], name='crm_consent_contact_0e83c8_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['status', '-created_at'], name='crm_consent_status_df8838_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['contact', '-created_at'], name='crm_activit_contact_de966a_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['event_type', '-created_at'], name='crm_activit_event_t_a60d2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationcontact',
            constraint=models.UniqueConstraint(fields=('organization', 'contact'), name='crm_unique_organization_contact'),
        ),
        migrations.AddConstraint(
            model_name='organizationcontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organization',), name='crm_unique_primary_contact_per_organization'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['platform', 'status'], name='crm_store_platfor_cd8453_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['primary_contact', 'status'], name='crm_store_primary_c5e949_idx'),
        ),
    ]
