# Generated by Django 5.2.17 on 2026-08-13 04:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=8)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=64)),
                ('portal_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_preference', to='crm.contact')),
                ('default_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_customer_preferences', to='crm.store')),
            ],
            options={
                'ordering': ['contact__full_name'],
                'indexes': [models.Index(fields=['language', 'timezone'], name='customer_po_languag_fa30a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_services', to='crm.contact')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_contacts', to='services.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contact', '-created_at'], name='customer_po_contact_5f2795_idx'), models.Index(fields=['service', '-created_at'], name='customer_po_service_df05c7_idx')],
                'constraints': [models.UniqueConstraint(fields=('contact', 'service'), name='portal_unique_saved_service')],
            },
        ),
    ]
