# Generated by Django 5.2.17 on 2026-08-13 04:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_session_id', models.CharField(blank=True, max_length=64)),
                ('event_name', models.CharField(max_length=80)),
                ('page_path', models.CharField(blank=True, max_length=500)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=160)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='crm.contact')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='services.service')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_name', '-occurred_at'], name='analytics_a_event_n_cef4c9_idx'), models.Index(fields=['contact', '-occurred_at'], name='analytics_a_contact_65c97b_idx'), models.Index(fields=['service', '-occurred_at'], name='analytics_a_service_985fb5_idx'), models.Index(fields=['anonymous_session_id', '-occurred_at'], name='analytics_a_anonymo_357170_idx')],
            },
        ),
    ]
